version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - /home/mahammad/casestudy:/csv_data

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes: {}